name: Coverage

on:
  workflow_run:
    workflows: ["Checks"]
    types:
      - completed
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run workspace tarpaulin coverage
  coverage:
    environment: symbolica_keys
    runs-on: ubuntu-latest
    # Only run if tests completed successfully
    if: github.event.workflow_run.conclusion == 'success'
    env:
      SYMBOLICA_LICENSE: ${{ secrets.SYMBOLICA_LICENSE }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: lcnbr
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Run workspace tarpaulin coverage
        run: nix build .#checks.x86_64-linux.workspace-tarpaulin --impure --print-build-logs
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./result/cobertura.xml
          fail_ci_if_error: true
